[[project]]
name = "altoku"
desc = "A TUI japanese media aggregate."
tags = ["tui", "ratatui", "rust", "manga", "anime", "ani-cli"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/altoku" },
]

[[project]]
name = "bunbun"
desc = "A simple and adorable sysinfo utility."
tags = ["sysinfo", "neofetch", "rust", "cli"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/bunbun" },
]

[[project]]
name = "vaporise"
desc = "A simple, featureful and blazingly fast memory-safe alternative to `rm`."
tags = ["rm", "rust", "alternative", "cli"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/vaporise" },
]

[[project]]
name = "Ambition"
desc = "A textual fast-paced 2D MMORPG."
tags = ["rust", "bevy", "mmorpg"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/ambition" },
]

[[project]]
name = "sage"
desc = "A collection of utilities for my home lab."
tags = ["rust", "homelab", "selfhosted", "utility", "cli"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/sage" },
]

[[project]]
name = "rustboyadvance-ng"
desc = "A rusty Nintendo™ Game Boy Advance emulator and debugger. `[Deprecated]`"
tags = ["rust", "gameboy", "emulator"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/rustboyadvance-ng" },
  { name = "parent", url = "https://github.com/michelhe/rustboyadvance-ng" },
]

[[project]]
name = "radiant.nvim"
desc = "A fast and minimal Neovim configuration framework."
tags = ["neovim"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/radiant.nvim" },
]

[[project]]
name = "kagayaki.nvim"
desc = "A gorgeously soft colorscheme for Neovim."
tags = ["neovim", "colorscheme"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/particle.nvim" },
]

[[project]]
name = "DianciEmacs"
desc = "A minimal and elegant Emacs configuration framework. `[Deprecated]`"
tags = ["emacs", "config", "diancie"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/dianciemacs" },
]

[[project]]
name = "Kagayaki for Emacs"
desc = "A gorgeously soft colorscheme for Emacs. `[Deprecated]`"
tags = ["emacs", "colorscheme", "theme", "dark"]
links = [
  { name = "git", url = "https://git.devraza.giize.com/devraza/kagayaki-emacs" },
]
