[[project]]
name = "particle.nvim"
desc = "A gorgeously soft colorscheme for Neovim."
tags = ["neovim"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/particle.nvim" },
]

[[project]]
name = "Ambition"
desc = "A textual fast-paced 2D MMORPG written in Rust."
tags = ["rust", "bevy", "mmorpg"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/ambition" },
]

[[project]]
name = "DianciEmacs"
desc = "A minimal and elegant Emacs configuration framework. **[Deprecated]**"
tags = ["emacs", "config"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/dianciemacs" },
]
