[[project]]
name = "vaporise"
desc = "A simple, featureful and blazingly fast memory-safe alternative to `rm` written in Rust."
tags = ["rm", "rust", "alternative", "cli"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/vaporise" },
]

[[project]]
name = "Ambition"
desc = "A textual fast-paced 2D MMORPG written in Rust."
tags = ["rust", "bevy", "mmorpg"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/ambition" },
]

[[project]]
name = "radiant.nvim"
desc = "A fast and minimal Neovim configuration framework."
tags = ["neovim"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/radiant.nvim" },
]

[[project]]
name = "kagayaki.nvim"
desc = "A gorgeously soft colorscheme for Neovim."
tags = ["neovim", "colorscheme"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/particle.nvim" },
]

[[project]]
name = "DianciEmacs"
desc = "A minimal and elegant Emacs configuration framework. `[Deprecated]`"
tags = ["emacs", "config", "diancie"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/dianciemacs" },
]

[[project]]
name = "Kagayaki for Emacs"
desc = "A gorgeously soft colorscheme for Emacs. `[Deprecated]`"
tags = ["emacs", "colorscheme", "theme", "dark"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/kagayaki-emacs" },
]
