[[project]]
name = "DianciEmacs"
desc = "A minimal and elegant Emacs configuration framework."
tags = ["emacs", "config", "diancie"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/dianciemacs" },
]

[[project]]
name = "Kagayaki for Emacs"
desc = "A gorgeously soft colorscheme for Emacs."
tags = ["emacs", "colorscheme", "theme", "dark"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/kagayaki-emacs" },
]

[[project]]
name = "Ambition"
desc = "A textual fast-paced 2D MMORPG written in Rust."
tags = ["rust", "bevy", "mmorpg"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/ambition" },
]

[[project]]
name = "quark.nvim"
desc = "A fast and minimal Neovim configuration framework. `[Deprecated]`"
tags = ["neovim"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/quark.nvim" },
]

[[project]]
name = "particle.nvim"
desc = "A gorgeously soft colorscheme for Neovim. `[Deprecated]`"
tags = ["neovim", "colorscheme"]
links = [
  { name = "git", url = "https://git.devraza.duckdns.org/devraza/particle.nvim" },
]
